apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory-app
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/DevSecOps18Project1/microservices.git
    path: backend/k8s
    targetRevision: main
  - repoURL: https://github.com/DevSecOps18Project1/microservices.git
    path: database/k8s
    targetRevision: main
  - repoURL: https://github.com/DevSecOps18Project1/microservices.git
    path: prometheus/k8s
    targetRevision: main
  - repoURL: https://github.com/DevSecOps18Project1/microservices.git
    path: grafana/k8s
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
